# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9dec2c33db4925a0b0db2f1ebc0910e51f1c698f34c04d16eb90cd3481687f08d54d5f906754440c02b87322c0b16dad95188cb19aa9129fbb85d8d431c1be3c

test:
  secret_key_base: 7ea785185779dea9a61ac6f912e6f5a75c3b01afa40783fd774670ce62592a3553d52c4b65b82f983263eb94114352a06e2384fb844b46da7656d575c1ae1f63

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
